### ISSUE TITLE
Corners always disabled

### ISSUE THREAD

**Issue by somepaulo** [ewlsh/dynamic-panel-transparency#104]
On Arch with Gnome 3.34.1 using stock Adwaita Shell & GTK themes the corners are always disabled no matter what the setting is, so the panel is always straight.
Changing other settings doesn't bring them back, only disabling the extension.
Disabling other extensions doesn't help either.

**Comment by rockon999** [comment]
Hi! I've received another report about this. Corner support is indeed broken in 3.34, I'll try to fix it soon! You can disable corners in settings temporarily and that should prevent any errors.

**Comment by ewlsh** [comment]
Fixed in #126
