### ISSUE TITLE
Panel transparency in overview

### ISSUE THREAD

**Issue by fawtytoo** [ewlsh/dynamic-panel-transparency#113]
I'm using Debian Buster Gnome Shell v3.30.
Panel transparency doesn't work in the overview. It stays darker and unaffected.

**Comment by rareza35** [comment]
Check the post #111 here, it is the moment solution.

**Comment by rockon999** [comment]
Hi @fawtytoo if you could provide any logs or relevant info that'd be very helpful! You could also try an older version of the extension.

**Comment by fawtytoo** [comment]
It works with version 20, but I get an error opening the settings:
`Gio.IOErrorEnum: Error opening file /home/steve/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/prefs.js: Is a directory

Stack trace:
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:67:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:82:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43`
