### ISSUE TITLE
Clock, power, battery and sound buttons missing

### ISSUE THREAD

**Issue by wojtekweg** [ewlsh/dynamic-panel-transparency#119]
I was messing a bit for a while with dynamic-panel-transparency settings. After I went away from computer and came back 15 minutes later* some buttons and clock just disappeared. The only two buttons that were left were Pop_OS tile windows button and Mpris Indicator Button. The rest was gone. 

I had some extensions installed with the dynaminc-panel-transparency along, but I think that was the extension that corrupted the panel, because the bug occurred just after installation of the extension. 

Extensions that I installed along and had running:
- Hide Activities Button
- Mpris Indicator Button
- Sound Input & Output Device Chooser
- Transparent GNOME panel (that was disabled)

Pop_OS built-in:
- Pop Battery Icon Fix
- Pop Shell
- Pop Shop Details
- System76 Power
- Ubuntu AppIndicators

I had "Do not disturb" mode enabled and running the newest version of Gnome and Pop_OS. Locking and unlocking the device didn't help. I had to restart the Gnome shell to fix that issue. 

*That may be caused, because there is a long time delay between setting the preferences and applying the actual change.

**Comment by ewlsh** [comment]
It is really unlikely that this extension caused buttons to disappear from the panel. The only thing this extension does to the panel icons is alter their color using styles, it doesn't touch any of the add/remove APIs (or any of the buttons even).

At the very least these extensions deal with adding and removing buttons:

- AppIndicators
- Hide Activities Button
- Mpris Indicator Button

If you can capture any logs if this happens again, that would help identify the cause. Screenshots too! But again, this extension shouldn't cause anything to be removed from the panel.
