### ISSUE TITLE
Where are the config settings in Tweak or DConf

### ISSUE THREAD

**Issue by jrgleason** [ewlsh/dynamic-panel-transparency#133]
I just installed the plugin and I can activate it and see it work using tweak. Now I would like to change some settings but I can't find anything in Tweak. I tried to use DConf and go to org>gnome>shell>extensions but I don't see dynamic panel.

Sorry for the crappy question but I am lost.

**Comment by jrgleason** [comment]
P.S. I am looking to set the background color of the topbar

**Comment by ewlsh** [comment]
Sorry for the delay...

It is under `/org/gnome/shell/extensions/dynamic-panel-transparency`, you may have to log in and out for `dconf` to pick it up.
