### ISSUE TITLE
Icons on panel aren't updating after quitting full screen of some application.

### ISSUE THREAD

**Issue by Soupy710** [ewlsh/dynamic-panel-transparency#134]
I noticed a bug today where the time, battery percentage, and others aren't updated on going to full screen of applications like vlc, youtube etc. I noticed this when I watched a youtube video on full screen for 10min and quit it. The panel was showing time that was 10min before.. I had to hover over it to update it... Same with the battery levels too...

**Comment by Soupy710** [comment]
Working fine now!

**Comment by ewlsh** [comment]
This happens sometimes after configurations are adjusted because GNOME Shell doesn't reload CSS changes particularly well.
