### ISSUE TITLE
Can't display settings in extension

### ISSUE THREAD

**Issue by villandra** [ewlsh/dynamic-panel-transparency#145]
I installed using git clone and moving folder as instructed.  

Now my top bar is semi-transparent, atleast it's the same color as background and not black.   

But when I clicked on settings button to try to make it genuinely transparent, I get, We're very sorry, but there's a problem:  The settings for this extension can't be displayed.  We recommend that you report the issue to the extension authors.  

I am using Ubuntu 20.04.2, newly upgraded from 18.04, and Gnome version 3.36.8.    

I previously tried by another method using a download where the page required selecting Gnome version AND what version of software you want with no guidance how to choose and it simply didn't work at all, and the folder structure was different.  I removed that folder before moving this folder.

Gtk.BuilderError: /home/dora/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/prefs.ui:115:1 Invalid object type 'GtkNotebookPage'

Stack trace:
  buildPrefsWidget@/home/dora/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/prefs.js:78:13
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by TimBoeh** [comment]
Exact the same problem on my end. Running Manjaro Gnome 40.3.0.
I could change setting before Manjaro moved to Gnome 40, but now I am stuck with a transparent panel (which I like) but of which I would like to change font color. Anyway, a solution would be highly appreciated.
Cheers

**Comment by ewlsh** [comment]
This was due to the GTK4 migration in GNOME 40, this is supported in newer versions.
