### ISSUE TITLE
Gnome 41 Support

### ISSUE THREAD

**Issue by schwrzstrbn** [ewlsh/dynamic-panel-transparency#150]
Do you have any plan to support Gnome 41?
I hope you will release a support for it.

**Comment by avbor** [comment]
+1
Fedora 35 is coming with Gnome 41...

**Comment by scottbeamer** [comment]
Not compatible with GNOME 41.  That's too bad.  I really hope that is fixed soon.

**Comment by ghostx31** [comment]
It can be fixed by adding `"41"` inside the `"shell-version"` in metadata,json of the extension.

**Comment by ewlsh** [comment]
I have work on 41, will probably push initial work to a branch tonight or tomorrow.

I'm working on applying fixes for corners and other improvements that have been pending.

For now adding "41" or allowing unsupported extension versions will work, albeit with some bugs

**Comment by ewlsh** [comment]
Initial GNOME 41 support should now be in `main`.

**Comment by Awoolyx** [comment]
Update made it work again, can't notice any bugs. Thank you! _(For some reason hasn't reached the GNOME Extensions website yet however)_

**Comment by ewlsh** [comment]
GNOME 41 support is published on GNOME Extensions.
