### ISSUE TITLE
gnome 42 support

### ISSUE THREAD

**Issue by olivertzeng** [ewlsh/dynamic-panel-transparency#155]

**Comment by anein** [comment]
Sure. I like the extension and I'd be pleased to use it on Gnome 42.

![Screenshot from 2022-06-21 23-34-45](https://user-images.githubusercontent.com/435658/174892676-315b5930-790e-442e-9ac7-283cf60fb641.png)

**Comment by ewlsh** [comment]
GNOME 42 and GNOME 43 are now supported :sweat_smile:
