### ISSUE TITLE
Error after installed

### ISSUE THREAD

**Issue by kenzhang98** [ewlsh/dynamic-panel-transparency#95]
Hi everyone, love this tool. But after I messed around with the panel and tweaked the transparency with a couple of extensions, apparently my panel is messed up right now. I deleted dynamic-panel-transparency in order to fix the error, but right now whenever I reinstall the tool, it shows a red error message, and the extension is not working at all. I am wondering if anyone has any idea how to fix this problem, or how to set my panel setting back to default. Thanks in advance!

**Comment by rockon999** [comment]
Removing the extension and restarting will remove any changes this extension has made.

As for why it isn't working...

`journalctl --since "30 seconds ago"` will print the most recent system logs. If you do this after running the extension and send the errors I can attempt to debug them.
